version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: ./back-docker
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - ./back-app:/usr/src/app
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/app

  frontend:
    build:
      context: ./front-docker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./front-app:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true 

volumes:
  mongodb-data:
